# Generated by Django 2.2.3 on 2019-08-02 08:40

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to=portfolio.models.Portfolio.date_upload_to),
        ),
    ]
